# Generated by Django 2.0.13 on 2020-03-04 17:10

import ddcz.models.magic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0025_source_as_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmety',
            options={},
        ),
        migrations.AddField(
            model_name='predmety',
            name='precteno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='autmail',
            field=ddcz.models.magic.MisencodedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='autor',
            field=ddcz.models.magic.MisencodedCharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='delka',
            field=ddcz.models.magic.MisencodedCharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='jmeno',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='kz',
            field=ddcz.models.magic.MisencodedCharField(blank=True, db_column='KZ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='pochvez',
            field=ddcz.models.magic.MisencodedIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='popis',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='schvaleno',
            field=ddcz.models.magic.MisencodedCharField(choices=[('a', 'Schváleno'), ('n', 'Neschváleno')], max_length=1),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='skupina',
            field=ddcz.models.magic.MisencodedTextField(),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='tisknuto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='uc',
            field=ddcz.models.magic.MisencodedTextField(blank=True, db_column='UC', null=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='zdroj',
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predmety',
            name='zdrojmail',
            field=ddcz.models.magic.MisencodedTextField(blank=True, null=True),
        ),
    ]
