# Generated by Django 2.0.13 on 2020-03-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddcz', '0026_gameitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predmety',
            new_name='GameItem',
        ),
    ]
